// generated by Proto2Typescript. do not touch!

declare module datariver {
	interface ProtoBufModel {
		toArrayBuffer(): ArrayBuffer;
		//toBuffer(): NodeBuffer;
		//encode(): ByteBuffer;
		toBase64(): string;
		toString(): string;
	}

	export interface ProtoBufBuilder {
		Geo: GeoBuilder;
		Listing: ListingBuilder;
		ListingResponse: ListingResponseBuilder;
		GetListingRequest: GetListingRequestBuilder;
		DeleteListingRequest: DeleteListingRequestBuilder;
		
	}
}

declare module datariver {

	export interface Geo extends ProtoBufModel {
		latitude?: number;
		getLatitude() : number;
		setLatitude(latitude : number): void;
		longitude?: number;
		getLongitude() : number;
		setLongitude(longitude : number): void;
		
	}
	
	export interface GeoBuilder {
		new(): Geo;
		decode(buffer: ArrayBuffer) : Geo;
		//decode(buffer: NodeBuffer) : Geo;
		//decode(buffer: ByteArrayBuffer) : Geo;
		decode64(buffer: string) : Geo;
		
	}	
}

declare module datariver {

	export interface Listing extends ProtoBufModel {
		vendasta_id?: string;
		getVendastaId() : string;
		setVendastaId(vendastaId : string): void;
		external_id?: string;
		getExternalId() : string;
		setExternalId(externalId : string): void;
		url?: string;
		getUrl() : string;
		setUrl(url : string): void;
		company_name?: string;
		getCompanyName() : string;
		setCompanyName(companyName : string): void;
		address?: string;
		getAddress() : string;
		setAddress(address : string): void;
		city?: string;
		getCity() : string;
		setCity(city : string): void;
		state?: string;
		getState() : string;
		setState(state : string): void;
		country?: string;
		getCountry() : string;
		setCountry(country : string): void;
		zip_code?: string;
		getZipCode() : string;
		setZipCode(zipCode : string): void;
		location?: Geo;
		getLocation() : Geo;
		setLocation(location : Geo): void;
		phone?: string;
		getPhone() : string;
		setPhone(phone : string): void;
		additional_phone_numbers: string[];
		getAdditionalPhoneNumbers() : string[];
		setAdditionalPhoneNumbers(additionalPhoneNumbers : string[]): void;
		website?: string;
		getWebsite() : string;
		setWebsite(website : string): void;
		number_of_reviews?: number;
		getNumberOfReviews() : number;
		setNumberOfReviews(numberOfReviews : number): void;
		average_review_rating?: number;
		getAverageReviewRating() : number;
		setAverageReviewRating(averageReviewRating : number): void;
		business_categories: string[];
		getBusinessCategories() : string[];
		setBusinessCategories(businessCategories : string[]): void;
		
	}
	
	export interface ListingBuilder {
		new(): Listing;
		decode(buffer: ArrayBuffer) : Listing;
		//decode(buffer: NodeBuffer) : Listing;
		//decode(buffer: ByteArrayBuffer) : Listing;
		decode64(buffer: string) : Listing;
		
	}	
}

declare module datariver {

	export interface ListingResponse extends ProtoBufModel {
		vendasta_id?: string;
		getVendastaId() : string;
		setVendastaId(vendastaId : string): void;
		external_id?: string;
		getExternalId() : string;
		setExternalId(externalId : string): void;
		status?: ListingResponse.StatusCodes;
		getStatus() : ListingResponse.StatusCodes;
		setStatus(status : ListingResponse.StatusCodes): void;
		error?: string;
		getError() : string;
		setError(error : string): void;
		listing?: Listing;
		getListing() : Listing;
		setListing(listing : Listing): void;
		
	}
	
	export interface ListingResponseBuilder {
		new(): ListingResponse;
		decode(buffer: ArrayBuffer) : ListingResponse;
		//decode(buffer: NodeBuffer) : ListingResponse;
		//decode(buffer: ByteArrayBuffer) : ListingResponse;
		decode64(buffer: string) : ListingResponse;
		StatusCodes: ListingResponse.StatusCodes;
		
	}	
}

declare module datariver.ListingResponse {
	export const enum StatusCodes {
		UNUSED = 0,
		SUCCESS = 1,
		ERROR = 2,
		REJECTED = 3,
		NOT_FOUND = 4,
		
	}
}

declare module datariver {

	export interface GetListingRequest extends ProtoBufModel {
		vendasta_id?: string;
		getVendastaId() : string;
		setVendastaId(vendastaId : string): void;
		
	}
	
	export interface GetListingRequestBuilder {
		new(): GetListingRequest;
		decode(buffer: ArrayBuffer) : GetListingRequest;
		//decode(buffer: NodeBuffer) : GetListingRequest;
		//decode(buffer: ByteArrayBuffer) : GetListingRequest;
		decode64(buffer: string) : GetListingRequest;
		
	}	
}

declare module datariver {

	export interface DeleteListingRequest extends ProtoBufModel {
		vendasta_id?: string;
		getVendastaId() : string;
		setVendastaId(vendastaId : string): void;
		
	}
	
	export interface DeleteListingRequestBuilder {
		new(): DeleteListingRequest;
		decode(buffer: ArrayBuffer) : DeleteListingRequest;
		//decode(buffer: NodeBuffer) : DeleteListingRequest;
		//decode(buffer: ByteArrayBuffer) : DeleteListingRequest;
		decode64(buffer: string) : DeleteListingRequest;
		
	}	
}
