// generated by Proto2Typescript. do not touch!

declare module datariver {
	interface ProtoBufModel {
		toArrayBuffer(): ArrayBuffer;
		//toBuffer(): NodeBuffer;
		//encode(): ByteBuffer;
		toBase64(): string;
		toString(): string;
	}

	export interface ProtoBufBuilder {
		Geo: GeoBuilder;
		Listing: ListingBuilder;
		ListingResponse: ListingResponseBuilder;
		GetListingRequest: GetListingRequestBuilder;
		DeleteListingRequest: DeleteListingRequestBuilder;
		
	}
}

declare module datariver {

	export interface Geo extends ProtoBufModel {
		latitude?: number;
		longitude?: number;
		
	}
	
	export interface GeoBuilder {
		new(): Geo;
		decode(buffer: ArrayBuffer) : Geo;
		//decode(buffer: NodeBuffer) : Geo;
		//decode(buffer: ByteArrayBuffer) : Geo;
		decode64(buffer: string) : Geo;
		
	}	
}

declare module datariver {

	export interface Listing extends ProtoBufModel {
		listing_id?: string;
		external_id?: string;
		url?: string;
		company_name?: string;
		address?: string;
		city?: string;
		state?: string;
		country?: string;
		zip_code?: string;
		location?: Geo;
		phone?: string;
		additional_phone_numbers: string[];
		website?: string;
		number_of_reviews?: number;
		average_review_rating?: number;
		business_categories: string[];
		
	}
	
	export interface ListingBuilder {
		new(): Listing;
		decode(buffer: ArrayBuffer) : Listing;
		//decode(buffer: NodeBuffer) : Listing;
		//decode(buffer: ByteArrayBuffer) : Listing;
		decode64(buffer: string) : Listing;
		
	}	
}

declare module datariver {

	export interface ListingResponse extends ProtoBufModel {
		listing_id?: string;
		external_id?: string;
		status?: ListingResponse.StatusCodes;
		error?: string;
		listing?: Listing;
		
	}
	
	export interface ListingResponseBuilder {
		new(): ListingResponse;
		decode(buffer: ArrayBuffer) : ListingResponse;
		//decode(buffer: NodeBuffer) : ListingResponse;
		//decode(buffer: ByteArrayBuffer) : ListingResponse;
		decode64(buffer: string) : ListingResponse;
		StatusCodes: ListingResponse.StatusCodes;
		
	}	
}

declare module datariver.ListingResponse {
	export const enum StatusCodes {
		UNUSED = 0,
		SUCCESS = 1,
		ERROR = 2,
		REJECTED = 3,
		NOT_FOUND = 4,
		
	}
}

declare module datariver {

	export interface GetListingRequest extends ProtoBufModel {
		listing_id?: string;
		
	}
	
	export interface GetListingRequestBuilder {
		new(): GetListingRequest;
		decode(buffer: ArrayBuffer) : GetListingRequest;
		//decode(buffer: NodeBuffer) : GetListingRequest;
		//decode(buffer: ByteArrayBuffer) : GetListingRequest;
		decode64(buffer: string) : GetListingRequest;
		
	}	
}

declare module datariver {

	export interface DeleteListingRequest extends ProtoBufModel {
		listing_id?: string;
		
	}
	
	export interface DeleteListingRequestBuilder {
		new(): DeleteListingRequest;
		decode(buffer: ArrayBuffer) : DeleteListingRequest;
		//decode(buffer: NodeBuffer) : DeleteListingRequest;
		//decode(buffer: ByteArrayBuffer) : DeleteListingRequest;
		decode64(buffer: string) : DeleteListingRequest;
		
	}	
}
