// generated by Proto2Typescript. do not touch!

declare module Proto2TypeScript {
	interface ProtoBufModel {
		toArrayBuffer(): ArrayBuffer;
		//toBuffer(): NodeBuffer;
		//encode(): ByteBuffer;
		toBase64(): string;
		toString(): string;
	}

	export interface ProtoBufBuilder {
		google: googleBuilder;
		datariver: datariverBuilder;
		
	}
}

declare module Proto2TypeScript {

	export interface google extends ProtoBufModel {
		
	}
	
	export interface googleBuilder {
		new(): google;
		decode(buffer: ArrayBuffer) : google;
		//decode(buffer: NodeBuffer) : google;
		//decode(buffer: ByteArrayBuffer) : google;
		decode64(buffer: string) : google;
		protobuf: google.protobufBuilder;
		
	}	
}

declare module Proto2TypeScript.google {

	export interface protobuf extends ProtoBufModel {
		
	}
	
	export interface protobufBuilder {
		new(): protobuf;
		decode(buffer: ArrayBuffer) : protobuf;
		//decode(buffer: NodeBuffer) : protobuf;
		//decode(buffer: ByteArrayBuffer) : protobuf;
		decode64(buffer: string) : protobuf;
		Empty: protobuf.EmptyBuilder;
		
	}	
}

declare module Proto2TypeScript.google.protobuf {

	export interface Empty extends ProtoBufModel {
		
	}
	
	export interface EmptyBuilder {
		new(): Empty;
		decode(buffer: ArrayBuffer) : Empty;
		//decode(buffer: NodeBuffer) : Empty;
		//decode(buffer: ByteArrayBuffer) : Empty;
		decode64(buffer: string) : Empty;
		
	}	
}

declare module Proto2TypeScript {

	export interface datariver extends ProtoBufModel {
		
	}
	
	export interface datariverBuilder {
		new(): datariver;
		decode(buffer: ArrayBuffer) : datariver;
		//decode(buffer: NodeBuffer) : datariver;
		//decode(buffer: ByteArrayBuffer) : datariver;
		decode64(buffer: string) : datariver;
		Geo: datariver.GeoBuilder;
		Listing: datariver.ListingBuilder;
		GetListingRequest: datariver.GetListingRequestBuilder;
		DeleteListingRequest: datariver.DeleteListingRequestBuilder;
		
	}	
}

declare module Proto2TypeScript.datariver {

	export interface Geo extends ProtoBufModel {
		latitude?: number;
		longitude?: number;
		
	}
	
	export interface GeoBuilder {
		new(): Geo;
		decode(buffer: ArrayBuffer) : Geo;
		//decode(buffer: NodeBuffer) : Geo;
		//decode(buffer: ByteArrayBuffer) : Geo;
		decode64(buffer: string) : Geo;
		
	}	
}

declare module Proto2TypeScript.datariver {

	export interface Listing extends ProtoBufModel {
		listing_id?: string;
		external_id?: string;
		url?: string;
		company_name?: string;
		address?: string;
		city?: string;
		state?: string;
		country?: string;
		zip_code?: string;
		location?: Geo;
		phone?: string;
		additional_phone_numbers: string[];
		website?: string;
		number_of_reviews?: number;
		average_review_rating?: number;
		business_categories: string[];
		
	}
	
	export interface ListingBuilder {
		new(): Listing;
		decode(buffer: ArrayBuffer) : Listing;
		//decode(buffer: NodeBuffer) : Listing;
		//decode(buffer: ByteArrayBuffer) : Listing;
		decode64(buffer: string) : Listing;
		
	}	
}

declare module Proto2TypeScript.datariver {

	export interface GetListingRequest extends ProtoBufModel {
		listing_id?: string;
		
	}
	
	export interface GetListingRequestBuilder {
		new(): GetListingRequest;
		decode(buffer: ArrayBuffer) : GetListingRequest;
		//decode(buffer: NodeBuffer) : GetListingRequest;
		//decode(buffer: ByteArrayBuffer) : GetListingRequest;
		decode64(buffer: string) : GetListingRequest;
		
	}	
}

declare module Proto2TypeScript.datariver {

	export interface DeleteListingRequest extends ProtoBufModel {
		listing_id?: string;
		
	}
	
	export interface DeleteListingRequestBuilder {
		new(): DeleteListingRequest;
		decode(buffer: ArrayBuffer) : DeleteListingRequest;
		//decode(buffer: NodeBuffer) : DeleteListingRequest;
		//decode(buffer: ByteArrayBuffer) : DeleteListingRequest;
		decode64(buffer: string) : DeleteListingRequest;
		
	}	
}
