// generated by Proto2Typescript. do not touch!

declare module Proto2TypeScript {
	interface ProtoBufModel {
		toArrayBuffer(): ArrayBuffer;
		//toBuffer(): NodeBuffer;
		//encode(): ByteBuffer;
		toBase64(): string;
		toString(): string;
	}

	export interface ProtoBufBuilder {
		google: googleBuilder;
		datariver: datariverBuilder;
		
	}
}

declare module Proto2TypeScript {

	export interface google extends ProtoBufModel {
		
	}
	
	export interface googleBuilder {
		new(): google;
		decode(buffer: ArrayBuffer) : google;
		//decode(buffer: NodeBuffer) : google;
		//decode(buffer: ByteArrayBuffer) : google;
		decode64(buffer: string) : google;
		protobuf: google.protobufBuilder;
		
	}	
}

declare module Proto2TypeScript.google {

	export interface protobuf extends ProtoBufModel {
		
	}
	
	export interface protobufBuilder {
		new(): protobuf;
		decode(buffer: ArrayBuffer) : protobuf;
		//decode(buffer: NodeBuffer) : protobuf;
		//decode(buffer: ByteArrayBuffer) : protobuf;
		decode64(buffer: string) : protobuf;
		Empty: protobuf.EmptyBuilder;
		Timestamp: protobuf.TimestampBuilder;
		
	}	
}

declare module Proto2TypeScript.google.protobuf {

	export interface Empty extends ProtoBufModel {
		
	}
	
	export interface EmptyBuilder {
		new(): Empty;
		decode(buffer: ArrayBuffer) : Empty;
		//decode(buffer: NodeBuffer) : Empty;
		//decode(buffer: ByteArrayBuffer) : Empty;
		decode64(buffer: string) : Empty;
		
	}	
}

declare module Proto2TypeScript.google.protobuf {

	export interface Timestamp extends ProtoBufModel {
		seconds?: number;
		nanos?: number;
		
	}
	
	export interface TimestampBuilder {
		new(): Timestamp;
		decode(buffer: ArrayBuffer) : Timestamp;
		//decode(buffer: NodeBuffer) : Timestamp;
		//decode(buffer: ByteArrayBuffer) : Timestamp;
		decode64(buffer: string) : Timestamp;
		
	}	
}

declare module Proto2TypeScript {

	export interface datariver extends ProtoBufModel {
		
	}
	
	export interface datariverBuilder {
		new(): datariver;
		decode(buffer: ArrayBuffer) : datariver;
		//decode(buffer: NodeBuffer) : datariver;
		//decode(buffer: ByteArrayBuffer) : datariver;
		decode64(buffer: string) : datariver;
		Review: datariver.ReviewBuilder;
		GetReviewRequest: datariver.GetReviewRequestBuilder;
		DeleteReviewRequest: datariver.DeleteReviewRequestBuilder;
		ListReviewsRequest: datariver.ListReviewsRequestBuilder;
		ListReviewsResponse: datariver.ListReviewsResponseBuilder;
		
	}	
}

declare module Proto2TypeScript.datariver {

	export interface Review extends ProtoBufModel {
		review_id?: string;
		listing_id?: string;
		url?: string;
		star_rating?: number;
		reviewer_name?: string;
		reviewer_email?: string;
		reviewer_url?: string;
		content?: string;
		published_date?: google.protobuf.Timestamp;
		title?: string;
		
	}
	
	export interface ReviewBuilder {
		new(): Review;
		decode(buffer: ArrayBuffer) : Review;
		//decode(buffer: NodeBuffer) : Review;
		//decode(buffer: ByteArrayBuffer) : Review;
		decode64(buffer: string) : Review;
		
	}	
}

declare module Proto2TypeScript.datariver {

	export interface GetReviewRequest extends ProtoBufModel {
		review_id?: string;
		
	}
	
	export interface GetReviewRequestBuilder {
		new(): GetReviewRequest;
		decode(buffer: ArrayBuffer) : GetReviewRequest;
		//decode(buffer: NodeBuffer) : GetReviewRequest;
		//decode(buffer: ByteArrayBuffer) : GetReviewRequest;
		decode64(buffer: string) : GetReviewRequest;
		
	}	
}

declare module Proto2TypeScript.datariver {

	export interface DeleteReviewRequest extends ProtoBufModel {
		review_id?: string;
		
	}
	
	export interface DeleteReviewRequestBuilder {
		new(): DeleteReviewRequest;
		decode(buffer: ArrayBuffer) : DeleteReviewRequest;
		//decode(buffer: NodeBuffer) : DeleteReviewRequest;
		//decode(buffer: ByteArrayBuffer) : DeleteReviewRequest;
		decode64(buffer: string) : DeleteReviewRequest;
		
	}	
}

declare module Proto2TypeScript.datariver {

	export interface ListReviewsRequest extends ProtoBufModel {
		listing_id?: string;
		listing_external_id?: string;
		offset?: number;
		page_size?: number;
		
	}
	
	export interface ListReviewsRequestBuilder {
		new(): ListReviewsRequest;
		decode(buffer: ArrayBuffer) : ListReviewsRequest;
		//decode(buffer: NodeBuffer) : ListReviewsRequest;
		//decode(buffer: ByteArrayBuffer) : ListReviewsRequest;
		decode64(buffer: string) : ListReviewsRequest;
		
	}	
}

declare module Proto2TypeScript.datariver {

	export interface ListReviewsResponse extends ProtoBufModel {
		reviews: Review[];
		
	}
	
	export interface ListReviewsResponseBuilder {
		new(): ListReviewsResponse;
		decode(buffer: ArrayBuffer) : ListReviewsResponse;
		//decode(buffer: NodeBuffer) : ListReviewsResponse;
		//decode(buffer: ByteArrayBuffer) : ListReviewsResponse;
		decode64(buffer: string) : ListReviewsResponse;
		
	}	
}
